FIND_PATH(MYSQL_INCLUDE_DIR mysql/jdbc.h
        HINTS ENV MYSQL_DIR
        PATH_SUFFIXES
        Headers include
        PATHS
        /usr/local
        /usr
        /sw # Fink
        /opt/local # DarwinPorts
        /opt/csw # Blastwave
        /opt
        /..
        ${SDEXT_CUSTOM_3DPARTY_DIR})


MESSAGE(STATUS "BANANEN ${MYSQL_INCLUDE_DIR}")
FIND_LIBRARY(MYSQL_LIBCRYPTO_LIBRARY 
  NAMES libcrypto
  HINTS ENV MYSQL_DIR
  PATH_SUFFIXES lib64 lib libs64 libs libs/Win32 libs/Win64
  PATHS /usr /usr/local ${SDEXT_CUSTOM_3DPARTY_DIR})

MESSAGE(STATUS "BANANEN ${MYSQL_LIBCRYPTO_LIBRARY}")

FIND_LIBRARY(MYSQL_LIBSSL_LIBRARY
  NAMES libssl
  HINTS ENV MYSQL_DIR
  PATH_SUFFIXES lib64 lib libs64 libs libs/Win32 libs/Win64
  PATHS /usr /usr/local ${SDEXT_CUSTOM_3DPARTY_DIR})

MESSAGE(STATUS "BANANEN ${MYSQL_LIBSSL_LIBRARY}")

FIND_LIBRARY(MYSQL_CPPCONN_LIBRARY
  NAMES mysqlcppconn
  HINTS ENV MYSQL_DIR
  PATH_SUFFIXES lib64 lib libs64 libs libs/Win32 libs/Win64
  PATHS /usr /usr/local ${SDEXT_CUSTOM_3DPARTY_DIR})

MESSAGE(STATUS "BANANEN ${MYSQL_CPPCONN_LIBRARY}")

FIND_LIBRARY(MYSQL_CPPCONN8_LIBRARY
  NAMES mysqlcppconn8
  HINTS ENV MYSQL_DIR
  PATH_SUFFIXES lib64 lib libs64 libs libs/Win32 libs/Win64
  PATHS /usr /usr/local ${SDEXT_CUSTOM_3DPARTY_DIR})

MESSAGE(STATUS "BANANEN ${MYSQL_CPPCONN8_LIBRARY}")

FIND_LIBRARY(MYSQL_CPPCONN_STATIC_LIBRARY
  NAMES mysqlcppconn-static
  HINTS ENV MYSQL_DIR
  PATH_SUFFIXES lib64 lib libs64 libs libs/Win32 libs/Win64
  PATHS /usr /usr/local ${SDEXT_CUSTOM_3DPARTY_DIR})

MESSAGE(STATUS "BANANEN ${MYSQL_CPPCONN_STATIC_LIBRARY}")

FIND_LIBRARY(MYSQL_CPPCONN8_STATIC_LIBRARY
  NAMES mysqlcppconn8-static
  HINTS ENV MYSQL_DIR
  PATH_SUFFIXES lib64 lib libs64 libs libs/Win32 libs/Win64
  PATHS /usr /usr/local ${SDEXT_CUSTOM_3DPARTY_DIR})

MESSAGE(STATUS "BANANEN ${MYSQL_CPPCONN_STATIC_LIBRARY}")


SET(MYSQL_FOUND FALSE)
IF(MYSQL_LIBCRYPTO_LIBRARY 
   AND MYSQL_LIBSSL_LIBRARY
   AND MYSQL_CPPCONN_LIBRARY
   AND MYSQL_CPPCONN8_LIBRARY
   AND MYSQL_CPPCONN_STATIC_LIBRARY
   AND MYSQL_CPPCONN8_STATIC_LIBRARY)
    SET(MYSQL_FOUND TRUE)
ENDIF(MYSQL_LIBCRYPTO_LIBRARY 
   AND MYSQL_LIBSSL_LIBRARY
   AND MYSQL_CPPCONN_LIBRARY
   AND MYSQL_CPPCONN8_LIBRARY
   AND MYSQL_CPPCONN_STATIC_LIBRARY
   AND MYSQL_CPPCONN8_STATIC_LIBRARY)