name: CI Backend Pipeline Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow manually triggering from the actions tab
  workflow_dispatch:


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

  # Enable colour output for GTEST and XML file generation
  GTEST_COLOR: yes
  GTEST_OUTPUT: xml:test-results/

  CCACHE_LOGFILE: D:\a\speed-dreams\speed-dreams\ccache.log

jobs:
  build:
    # The CMake configure and build commands are platform agnostic anda should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: debug
      shell: bash
      run: cl

    - name: Configure CMake
      shell: bash
      run: cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DOPTION_PACKAGING=0 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBACKEND_ONLY_OPTION=TRUE -S '${{github.workspace}}/speed-dreams/source-2.2.3' -B '${{runner.workspace}}/build' -G Ninja

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -V

    - name: Upload log
      uses: actions/upload-artifact@v2
      with:
        name: ccache.log
        path: D:\a\speed-dreams\speed-dreams\ccache.log

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: ${{runner.workspace}}/build/IPCTests/test-results/**/*.xml
      
